const defaultWidth = 170
const defaultHeight = 64

export interface PortCompany {
  companyName: string
  src: string
  website: string
  width: number
  height: number
  acquiredBy?: string
}

export const PortfolioCompanies = [
  {
    companyName: 'ProsperOps',
    src: '/img/logos/prosper-ops.svg',
    website: 'https://www.prosperops.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cart',
    src: '/img/logos/cart.svg',
    website: 'https://cart.com/',
    width: 80,
    height: 80,
  },
  {
    companyName: 'Teleport',
    src: '/img/logos/teleport.svg',
    website: 'https://goteleport.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Founderpath',
    src: '/img/logos/founderpath.svg',
    website: 'https://founderpath.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Super Dispatch',
    src: '/img/logos/super-dispatch.svg',
    website: 'https://superdispatch.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Living Security',
    src: '/img/logos/living-security.svg',
    website: 'https://www.livingsecurity.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Finally',
    src: '/img/logos/finally.svg',
    website: 'https://finally.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Fathom',
    src: '/img/logos/fathom.svg',
    website: 'https://fathom.video/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Conductor One',
    src: '/img/logos/conductor-one.svg',
    website: 'https://www.conductorone.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Slang.ai',
    src: '/img/logos/slang-ai.svg',
    website: 'https://www.slang.ai/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cohley',
    src: '/img/logos/cohley.svg',
    website: 'https://www.cohley.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Better Leap',
    src: '/img/logos/betterleap-logo.svg',
    website: 'https://betterleap.com/',
    width: 64,
    height: 64,
  },

  {
    companyName: 'Zen Business',
    src: '/img/logos/zen-business.svg',
    website: 'https://www.zenbusiness.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Data Robot',
    src: '/img/logos/data-robot.svg',
    website: 'https://www.datarobot.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Altru',
    src: '/img/logos/altru.svg',
    website: 'https://www.icims.com/company/newsroom/icims-acquires-altru-labs/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'iCIMS'
  },
  {
    companyName: 'Testlio',
    src: '/img/logos/testlio.svg',
    website: 'https://testlio.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'ScaleFT',
    src: '/img/logos/scaleft.svg',
    website: 'https://www.okta.com/products/advanced-server-access/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Okta',
  },
  {
    companyName: 'Remote Team',
    src: '/img/logos/remote-team.svg',
    website: 'https://gusto.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Gusto',
  },
  {
    companyName: 'EdLink',
    src: '/img/logos/ed-link.svg',
    website: 'https://ed.link/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'FreshBooks',
    src: '/img/logos/freshbooks.svg',
    website: 'https://www.freshbooks.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'CloudSnap',
    src: '/img/logos/cloudsnap.svg',
    website: 'https://www.paylocity.com/resources/resource-library/press-release/paylocity-announces-acquisition-of-cloudsnap/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Paylocity'
  },
  {
    companyName: 'Hyperwrite AI',
    src: '/img/logos/hyperwrite.svg',
    website: 'https://www.hyperwriteai.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Reflex',
    src: '/img/logos/reflex.svg',
    website: 'https://www.workreflex.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cloud Campaign',
    src: '/img/logos/cloud-campaign.svg',
    website: 'https://www.cloudcampaign.com/',
    width: defaultWidth,
    height: defaultHeight,
  },

  {
    companyName: 'Tenfold',
    src: '/img/logos/tenfold.svg',
    website: 'https://www.tenfold.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Live Person',
  },
  {
    companyName: 'Schematic',
    src: '/img/logos/schematic.svg',
    website: 'https://schematichq.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Send Spark',
    src: '/img/logos/send-spark.svg',
    website: 'https://www.sendspark.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Float Me',
    src: '/img/logos/float-me.svg',
    website: 'https://www.floatme.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'StrikeDeck',
    src: '/img/logos/strike-deck.svg',
    website: 'https://www.medallia.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Medallia',
  },
  {
    companyName: 'Blockjoy',
    src: '/img/logos/blockjoy.svg',
    website: 'https://www.blockjoy.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Chartio',
    src: '/img/logos/chartio.svg',
    website: 'https://www.chartio.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Atlassian',
  },
  {
    companyName: 'VidGrid',
    src: '/img/logos/vidgrid.svg',
    website: 'https://www.paylocity.com/resources/resource-library/press-release/paylocity-announces-acquisition-of-vidgrid/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Paylocity',
  },
  {
    companyName: 'PingBoard',
    src: '/img/logos/ping-board.svg',
    website: 'https://pingboard.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Workleap',
  },
  {
    companyName: 'LoudCrowd',
    src: '/img/logos/loud-crowd.svg',
    website: 'https://loudcrowd.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cardsite',
    src: '/img/logos/cardsite.svg',
    website: 'https://cardsite.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Share Willow',
    src: '/img/logos/share-willow.svg',
    website: 'https://www.sharewillow.com/',
    width: defaultWidth,
    height: defaultHeight,
  },

  {
    companyName: 'Finmark',
    src: '/img/logos/finmark.svg',
    website: 'https://www.bill.com/press-release/bill-completes-acquisition-of-finmark',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Bill.com'
  },
  {
    companyName: 'Acquire',
    src: '/img/logos/acquire.svg',
    website: 'https://acquire.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Talisman',
    src: '/img/logos/talisman-logo.svg',
    website: 'https://www.gettalisman.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Handraise',
    src: '/img/logos/hand-raise.svg',
    website: 'https://www.handraise.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'MakeSwift',
    src: '/img/logos/make-swift.svg',
    website: 'https://www.makeswift.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'BigCommerce'
  },
  // {
  //   companyName: 'HavocShield',
  //   src: '/img/logos/havocshield.svg',
  //   website: 'https://www.havocshield.com/',
  //   width: defaultWidth,
  //   height: defaultHeight,
  // },

  {
    companyName: 'Bottle',
    src: '/img/logos/bottle.svg',
    website: 'https://bottle.com/',
    width: defaultWidth,
    height: defaultHeight,
  },

  {
    companyName: 'Flight Control',
    src: '/img/logos/flight-control.svg',
    website: 'https://www.flightcontrol.dev/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Phone Wagon',
    src: '/img/logos/phone-wagon.svg',
    website: 'https://www.callrail.com/blog/callrail-acquires-phonewagon',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'CallRail',
  },
  {
    companyName: 'CompanyDNA',
    src: '/img/logos/company-dna.svg',
    website: 'https://www.companydna.ai/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Sequence',
    src: '/img/logos/sequence.svg',
    website: 'https://sequence.film/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Profit',
    src: '/img/logos/profit.svg',
    website: 'https://www.profitnow.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Paymentus',
  },


  {
    companyName: 'RedDoor',
    src: '/img/logos/red-door.svg',
    website: 'https://www.opendoor.com/articles/welcome-home-reddoor',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'OpenDoor',
  },
  {
    companyName: 'Tetra Insights',
    src: '/img/logos/tetra.svg',
    website: 'https://www.tetrainsights.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Valist',
    src: '/img/logos/valist2.svg',
    website: 'https://app.valist.io/',
    width: 110,
    height: 42,
    acquiredBy: 'Hyperplay',
  },
  {
    companyName: 'Clowder',
    src: '/img/logos/clowder.svg',
    website: 'https://www.clowder.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'ASI',
  },
  {
    companyName: 'Olive',
    src: '/img/logos/olive.svg',
    website: 'https://olive.app/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cloudability',
    src: '/img/logos/cloudability.svg',
    website: 'https://www.apptio.com/products/cloudability/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Apptio',
  },
  {
    companyName: 'Filestack',
    src: '/img/logos/filestack.svg',
    website: 'https://www.filestack.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Idera',
  },
  {
    companyName: 'Growth Match',
    src: '/img/logos/growth-match.svg',
    website: 'https://www.growthmatch.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Ad Espresso',
    src: '/img/logos/ad-espresso.svg',
    website: 'https://adespresso.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Hootsuite'
  },
]