const defaultWidth = 170
const defaultHeight = 64

export interface PortCompany {
  companyName: string
  src: string
  website: string
  width: number
  height: number
  acquiredBy?: string
}

export const PortfolioCompanies = [
  {
    companyName: 'ProsperOps',
    src: '/img/logos/prosper-ops.svg',
    website: 'https://www.prosperops.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Flexera'
  },
  {
    companyName: 'Conductor One',
    src: '/img/logos/conductor-one.svg',
    website: 'https://www.conductorone.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cart',
    src: '/img/logos/cart.svg',
    website: 'https://cart.com/',
    width: 80,
    height: 80,
  },
  {
    companyName: 'Teleport',
    src: '/img/logos/teleport.svg',
    website: 'https://goteleport.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Fathom',
    src: '/img/logos/fathom.svg',
    website: 'https://fathom.video/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Slang.ai',
    src: '/img/logos/slang-ai.svg',
    website: 'https://www.slang.ai/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Super Dispatch',
    src: '/img/logos/super-dispatch.svg',
    website: 'https://superdispatch.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Living Security',
    src: '/img/logos/living-security.svg',
    website: 'https://www.livingsecurity.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Schematic',
    src: '/img/logos/schematic.svg',
    website: 'https://schematichq.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Growthsignals',
    src: '/img/logos/growth-signals.svg',
    website: 'https://www.growthsignals.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Acclaim',
    src: '/img/logos/acclaim.svg',
    website: 'https://www.withacclaim.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Daytona',
    src: '/img/logos/daytona.svg',
    website: 'https://www.daytona.io/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Dreambase',
    src: '/img/logos/dreambase.svg',
    website: 'https://dreambase.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Mixlayer',
    src: '/img/logos/mixlayer.svg',
    website: 'https://www.mixlayer.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Finally',
    src: '/img/logos/finally.svg',
    website: 'https://finally.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Antim Labs',
    src: '/img/logos/antim-labs.svg',
    website: 'https://www.antimlabs.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Strongsuit',
    src: '/img/logos/strongsuit.svg',
    website: 'https://strongsuit.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Datavine',
    src: '/img/logos/datavine.svg',
    website: 'https://datavine.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Send Spark',
    src: '/img/logos/send-spark.svg',
    website: 'https://www.sendspark.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Xenon'
  },
  {
    companyName: 'Altru',
    src: '/img/logos/altru.svg',
    website: 'https://www.icims.com/company/newsroom/icims-acquires-altru-labs/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'iCIMS'
  },
  {
    companyName: 'Embucket',
    src: '/img/logos/embucket.svg',
    website: 'https://www.embucket.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Testlio',
    src: '/img/logos/testlio.svg',
    website: 'https://testlio.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'ScaleFT',
    src: '/img/logos/scaleft.svg',
    website: 'https://www.okta.com/products/advanced-server-access/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Okta',
  },
  {
    companyName: 'Remote Team',
    src: '/img/logos/remote-team.svg',
    website: 'https://gusto.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Gusto',
  },
  {
    companyName: 'CloudSnap',
    src: '/img/logos/cloudsnap.svg',
    website: 'https://www.paylocity.com/resources/resource-library/press-release/paylocity-announces-acquisition-of-cloudsnap/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Paylocity'
  },
  {
    companyName: 'Runtype',
    src: '/img/logos/runtype.svg',
    website: 'https://www.runtype.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Share Willow',
    src: '/img/logos/share-willow.svg',
    website: 'https://www.sharewillow.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Reflex',
    src: '/img/logos/reflex.svg',
    website: 'https://www.workreflex.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cloud Campaign',
    src: '/img/logos/cloud-campaign.svg',
    website: 'https://www.cloudcampaign.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Fetchdesk',
    src: '/img/logos/fetchdesk.svg',
    website: 'https://www.fetchdeskai.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Founderpath',
    src: '/img/logos/founderpath.svg',
    website: 'https://founderpath.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'StrikeDeck',
    src: '/img/logos/strike-deck.svg',
    website: 'https://www.medallia.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Medallia',
  },
  {
    companyName: 'Chartio',
    src: '/img/logos/chartio.svg',
    website: 'https://www.chartio.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Atlassian',
  },
  {
    companyName: 'Dimension labs',
    src: '/img/logos/dimension-labs.svg',
    website: 'https://www.dimensionlabs.io/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'VidGrid',
    src: '/img/logos/vidgrid.svg',
    website: 'https://www.paylocity.com/resources/resource-library/press-release/paylocity-announces-acquisition-of-vidgrid/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Paylocity',
  },
  {
    companyName: 'PingBoard',
    src: '/img/logos/ping-board.svg',
    website: 'https://pingboard.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Workleap',
  },
  {
    companyName: 'Float Me',
    src: '/img/logos/float-me.svg',
    website: 'https://www.floatme.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'LoudCrowd',
    src: '/img/logos/loud-crowd.svg',
    website: 'https://loudcrowd.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Finmark',
    src: '/img/logos/finmark.svg',
    website: 'https://www.bill.com/press-release/bill-completes-acquisition-of-finmark',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Bill.com'
  },
  {
    companyName: 'Handraise',
    src: '/img/logos/hand-raise.svg',
    website: 'https://www.handraise.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'MakeSwift',
    src: '/img/logos/make-swift.svg',
    website: 'https://www.makeswift.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'BigCommerce'
  },
  {
    companyName: 'Sorce',
    src: '/img/logos/sorce.svg',
    website: 'https://www.sorce.jobs/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'XYZ Capital',
    src: '/img/logos/xyz-capital.svg',
    website: 'https://xyzcapital.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Bottle',
    src: '/img/logos/bottle.svg',
    website: 'https://bottle.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Cohley',
    src: '/img/logos/cohley.svg',
    website: 'https://www.cohley.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Better Leap',
    src: '/img/logos/betterleap-logo.svg',
    website: 'https://betterleap.com/',
    width: 64,
    height: 64,
  },
  {
    companyName: 'Flight Control',
    src: '/img/logos/flight-control.svg',
    website: 'https://www.flightcontrol.dev/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Phone Wagon',
    src: '/img/logos/phone-wagon.svg',
    website: 'https://www.callrail.com/blog/callrail-acquires-phonewagon',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'CallRail',
  },
  {
    companyName: 'Sequence',
    src: '/img/logos/sequence.svg',
    website: 'https://sequence.film/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Profit',
    src: '/img/logos/profit.svg',
    website: 'https://www.profitnow.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Paymentus',
  },


  {
    companyName: 'RedDoor',
    src: '/img/logos/red-door.svg',
    website: 'https://www.opendoor.com/articles/welcome-home-reddoor',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'OpenDoor',
  },
  {
    companyName: 'Ad Espresso',
    src: '/img/logos/ad-espresso.svg',
    website: 'https://adespresso.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Hootsuite'
  },
  {
    companyName: 'FreshBooks',
    src: '/img/logos/freshbooks.svg',
    website: 'https://www.freshbooks.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'Tenfold',
    src: '/img/logos/tenfold.svg',
    website: 'https://www.tenfold.com/',
    width: defaultWidth,
    height: defaultHeight,
    acquiredBy: 'Live Person',
  },
  {
    companyName: 'Zen Business',
    src: '/img/logos/zen-business.svg',
    website: 'https://www.zenbusiness.com/',
    width: defaultWidth,
    height: defaultHeight,
  },
  {
    companyName: 'StaffAI',
    src: '/img/logos/staff-ai.svg',
    website: 'https://staffai.so/',
    width: defaultWidth,
    height: defaultHeight,
  },
]